from pathlib import Path

DATA_BASE_NAME = "VISA_DATA_BASE"

COLLECTION_NAME = "VISA_RECORDS"

MONGODB_URL_KEY = "MONGODB_URL"


DATA_SET_NAME = "visaData.csv"
TRAIN_DATASET_NAME ="visa_train.csv"
TEST_DATASET_NAME = "visa_test.csv"
DATA_VALIDATION_STATUS_FILE = "status.txt"
SCHEMA_FILE = Path("config\schema.yaml")
PROCESSING_OBJ_FILE_NAME = "obj.dill"


"""
DATA_INGESTION REQUIRED CONTANTS STARTS WITH DATA_INGESTION

"""

DATA_INGESTION_DIR:str  = "Data_Ingestion"
DATA_INGESTION_MAIN_DATA_DIR:str  = "Main_Data"
DATA_INGESTION_INGESTED_DIR :str = "Ingested"
DATA_INGESTION_TRAIN_TEST_SPLIT_RATIO : float = 0.25
DATA_INGESTION_COLLECTION_NAME : str = "VISA_RECORDS"


"""
DATA VALIDATION REALTED CONSTANTS STARTS WITH DATA VALIDATION

"""
DATA_VALDATION_DIR: str = "Data_validation"
DATA_VAIDATION_DRIFT_DIR: str ="Data_Drift"
DATA_VALIDATION_DRIFT_FILE_NAME : str = "report.yaml"
DATA_VALIDATION_STATUS_DIR :str = "STATUS"


"""
DATA TRANSFORMATION RELATED CONSTANTS STARTS WITH DATA_TRANSFORMATION

"""

DATA_TRANSFORMATION_DIR : str = "Transformation"
DATA_TRANSFORMATION_TRANSFORMED_DATA_DIR :str = "Transformed"
DATA_TRANSFORMATION_TRANSFORMED_OBJECT_DIR : str ="Transformed_object"

