
DATA_BASE_NAME = "VISA_DATA_BASE"

COLLECTION_NAME = "VISA_RECORDS"

MONGODB_URL_KEY = "MONGODB_URL"


DATA_SET_NAME = "visaData.csv"
TRAIN_DATASET_NAME ="visa_train.csv"
TEST_DATASET_NAME = "visa_test.csv"


"""
DATA_INGESTION REQUIRED CONTANTS STARTS WITH DATA_INGESTION

"""

DATA_INGESTION_DIR:str  = "Data_Ingestion"
DATA_INGESTION_MAIN_DATA_DIR:str  = "Main_Data"
DATA_INGESTION_INGESTED_DIR :str = "Ingested"
DATA_INGESTION_TRAIN_TEST_SPLIT_RATIO : float = 0.25
DATA_INGESTION_COLLECTION_NAME : str = "VISA_RECORDS"
