from pathlib import Path

import os

DATA_BASE_NAME = "VISA_DATA_BASE"

COLLECTION_NAME = "VISA_RECORDS"

MONGODB_URL_KEY = "MONGODB_URL"


DATA_SET_NAME = "visaData.csv"
TRAIN_DATASET_NAME ="visa_train.csv"
TEST_DATASET_NAME = "visa_test.csv"
DATA_VALIDATION_STATUS_FILE = "status.txt"
SCHEMA_FILE = Path("config\schema.yaml")
PROCESSING_OBJ_FILE_NAME = "obj.dill"
MODEL_FILE_NAME = "model.pkl"
TARGET_COLUMN = "case_status"


AWS_ACCESS_KEY_ID_ENV_KEY = "AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY_ENV_KEY = "AWS_SECRET_ACCESS_KEY"
REGION_NAME = "eu-north-1"

"""
DATA_INGESTION REQUIRED CONTANTS STARTS WITH DATA_INGESTION

"""

DATA_INGESTION_DIR:str  = "Data_Ingestion"
DATA_INGESTION_MAIN_DATA_DIR:str  = "Main_Data"
DATA_INGESTION_INGESTED_DIR :str = "Ingested"
DATA_INGESTION_TRAIN_TEST_SPLIT_RATIO : float = 0.25
DATA_INGESTION_COLLECTION_NAME : str = "VISA_RECORDS"


"""
DATA VALIDATION REALTED CONSTANTS STARTS WITH DATA VALIDATION

"""
DATA_VALDATION_DIR: str = "Data_validation"
DATA_VAIDATION_DRIFT_DIR: str ="Data_Drift"
DATA_VALIDATION_DRIFT_FILE_NAME : str = "report.yaml"
DATA_VALIDATION_STATUS_DIR :str = "STATUS"


"""
DATA TRANSFORMATION RELATED CONSTANTS STARTS WITH DATA_TRANSFORMATION

"""

DATA_TRANSFORMATION_DIR : str = "Data_Transformation"
DATA_TRANSFORMATION_TRANSFORMED_DATA_DIR :str = "Transformed"
DATA_TRANSFORMATION_TRANSFORMED_OBJECT_DIR : str ="Transformed_object"

"""
MODEL TRAINER RELATED CONSTATNST STARTS WITH MODEL TRAINER

"""

MODEL_TRAINER_DIR : str = "Model_Trainer"
MODEL_TRAINER_TRAINED_DIR :str ="Trained_Model"
MODEL_TRAINER_TRAINED_MODEL_NAME: str ="model.pkl"
MODEL_TRAINER_EXPECTED_SCORE : float = 0.6
MODEL_TRAINER_MODEL_CONFIG_FILE_PATH: str = Path(os.path.join("config","model.yaml"))




MODEL_EVALUATION_CHANGED_THRESHOLD :float = 0.02
MODEL_PUSHER_S3_KEY = "model-registry"
MODEL_BUCKET_NAME ="visaprojectbucket"




