
all_columns:
  case_id: object        
  continent: object
  education_of_employee: object
  has_job_experience: object
  requires_job_training: object
  no_of_employees: int64
  yr_of_estab: int64
  region_of_employment: object
  prevailing_wage: float64
  unit_of_wage: object
  full_time_position: object
  case_status: object

Transform_column:

  - yr_of_estab

drop_columns:
  - case_id
  - yr_of_estab

numerical_columns:

  - no_of_employees
  - yr_of_estab
  - prevailing_wage

categorical_columns:

  - case_id
  - continent
  - education_of_employee
  - has_job_experience
  - requires_job_training
  - region_of_employment
  - unit_of_wage
  - full_time_position
  - case_status

ordinal_encoding:
  - has_job_experience
  - requires_job_training
  - full_time_position

one_hot_encode:
  - continent
  - education_of_employee
  - region_of_employment
  - unit_of_wage

numerical_columns_after_feature_engineering:
  - comapny_age
  - prevailing_wage
  - no_of_employees
  


Target_Column: 
  Target: case_status

ui:
  default_columns:
    continent: Asia
    education_of_employee: Master's
    has_job_experience: "N"
    requires_job_training: "Y"
    no_of_employees: 100
    region_of_employment: West
    prevailing_wage: 100
    unit_of_wage: 23
    full_time_position: "Y"
    comapny_age : 10
